# Generated by Django 5.2 on 2025-05-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_comments_result_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSESkillDevelopmentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
            ],
        ),
    ]
