# Generated by Django 5.2 on 2025-05-02 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cseskilldevelopmentcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='cseskilldevelopmentcourse',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
