# Generated by Django 5.2 on 2025-05-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cseskilldevelopmentcourse_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cseskilldevelopmentcourse',
            name='user',
        ),
    ]
